// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WireManager.Core.Data;

#nullable disable

namespace WireManager.Core.Migrations
{
    [DbContext(typeof(WireManagerContext))]
    [Migration("20260910215946_addUserIdentities")]
    partial class addUserIdentities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WireManager.Core.Models.Audit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Details")
                        .HasColumnType("longtext");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EntityId")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Audits");
                });

            modelBuilder.Entity("WireManager.Core.Models.AuthenticationSSO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("OidcAuthority")
                        .HasColumnType("longtext");

                    b.Property<string>("OidcClientId")
                        .HasColumnType("longtext");

                    b.Property<string>("OidcClientSecret")
                        .HasColumnType("longtext");

                    b.Property<bool>("OidcEnabled")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("AuthenticationSSOs");
                });

            modelBuilder.Entity("WireManager.Core.Models.ConfPeer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AllowedIPs")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ConfServerId")
                        .HasColumnType("int");

                    b.Property<string>("DNSAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastHandShake")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PersistentKeepAlive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ConfServerId");

                    b.ToTable("ConfPeers");
                });

            modelBuilder.Entity("WireManager.Core.Models.ConfServer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("EndPoint")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("listenPort")
                        .HasColumnType("int");

                    b.Property<string>("publicKey")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("rangeIP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ConfServers");
                });

            modelBuilder.Entity("WireManager.Core.Models.PeerTag", b =>
                {
                    b.Property<int>("PeerId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("PeerId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PeerTags");
                });

            modelBuilder.Entity("WireManager.Core.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Domain")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TargetIp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("WireManager.Core.Models.SystemConfig", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Key");

                    b.ToTable("SystemConfigs");
                });

            modelBuilder.Entity("WireManager.Core.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("WireManager.Core.Models.TagService", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("TagId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("TagServices");
                });

            modelBuilder.Entity("WireManager.Core.Models.UsageHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("DeltaRxBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("DeltaTxBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<long>("RxBytesRaw")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("TxBytesRaw")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PublicKey", "Timestamp");

                    b.ToTable("UsageHistories", (string)null);
                });

            modelBuilder.Entity("WireManager.Core.Models.UserIdentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserUUID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Issuer", "Subject")
                        .IsUnique();

                    b.ToTable("UserIdentities");
                });

            modelBuilder.Entity("WireManager.Core.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UUID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WireManager.Core.Models.ConfPeer", b =>
                {
                    b.HasOne("WireManager.Core.Models.ConfServer", "Server")
                        .WithMany("Peers")
                        .HasForeignKey("ConfServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("WireManager.Core.Models.PeerTag", b =>
                {
                    b.HasOne("WireManager.Core.Models.ConfPeer", "Peer")
                        .WithMany("PeerTags")
                        .HasForeignKey("PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WireManager.Core.Models.Tag", "Tag")
                        .WithMany("PeerTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Peer");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("WireManager.Core.Models.TagService", b =>
                {
                    b.HasOne("WireManager.Core.Models.Service", "Service")
                        .WithMany("TagServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WireManager.Core.Models.Tag", "Tag")
                        .WithMany("TagServices")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("WireManager.Core.Models.UsageHistory", b =>
                {
                    b.HasOne("WireManager.Core.Models.ConfPeer", "Peer")
                        .WithMany("UsageHistories")
                        .HasForeignKey("PublicKey")
                        .HasPrincipalKey("PublicKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Peer");
                });

            modelBuilder.Entity("WireManager.Core.Models.ConfPeer", b =>
                {
                    b.Navigation("PeerTags");

                    b.Navigation("UsageHistories");
                });

            modelBuilder.Entity("WireManager.Core.Models.ConfServer", b =>
                {
                    b.Navigation("Peers");
                });

            modelBuilder.Entity("WireManager.Core.Models.Service", b =>
                {
                    b.Navigation("TagServices");
                });

            modelBuilder.Entity("WireManager.Core.Models.Tag", b =>
                {
                    b.Navigation("PeerTags");

                    b.Navigation("TagServices");
                });
#pragma warning restore 612, 618
        }
    }
}
